# Generated by Django 5.2.5 on 2025-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], default='Autre', max_length=10)),
                ('date_birthday', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bonsoir',
        ),
    ]
